# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb29460dcfcb299f526d9a596c3a41b52f20071941ba2810492981ea97378ecbfbc08858be0aa65d94f97ce68708f23574949c1629bda69424ef392022bd85e2

test:
  secret_key_base: 35d1bfacaf701eea23a37cdd494d1dec443e3c157c3325693cdb9ed5286845b569d482726263c049c51a188e7ebd56e0279d71f560352a6defbb55b5e1f86561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
